// Code generated by biscuit. DO NOT EDIT.

package client

import (
	"context"
	"net/http"
	"net/url"
)

// AuthTokenCreateRequest carries the inputs of POST /auth/token.
type AuthTokenCreateRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// AuthTokenCreate calls POST /auth/token. Get a token
func (c *Client) AuthTokenCreate(ctx context.Context, req *AuthTokenCreateRequest) (*Response, error) {
	return c.do(ctx, "POST", "/auth/token", req.Query, req.Header, req.Body, nil)
}

// CelestialBodiesCreateRequest carries the inputs of POST /celestial-bodies.
type CelestialBodiesCreateRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// CelestialBodiesCreate calls POST /celestial-bodies. Create a celestial body
func (c *Client) CelestialBodiesCreate(ctx context.Context, req *CelestialBodiesCreateRequest) (*Response, error) {
	return c.do(ctx, "POST", "/celestial-bodies", req.Query, req.Header, req.Body, [][]string{{"apiKeyCookie"}, {"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"openIdConnect"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// MeListRequest carries the inputs of GET /me.
type MeListRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// MeList calls GET /me. Get authenticated user
func (c *Client) MeList(ctx context.Context, req *MeListRequest) (*Response, error) {
	return c.do(ctx, "GET", "/me", req.Query, req.Header, req.Body, [][]string{{"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// PlanetsCreateRequest carries the inputs of POST /planets.
type PlanetsCreateRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// PlanetsCreate calls POST /planets. Create a planet
func (c *Client) PlanetsCreate(ctx context.Context, req *PlanetsCreateRequest) (*Response, error) {
	return c.do(ctx, "POST", "/planets", req.Query, req.Header, req.Body, [][]string{{"apiKeyCookie"}, {"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"openIdConnect"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// PlanetsDeleteRequest carries the inputs of DELETE /planets/{planetId}.
type PlanetsDeleteRequest struct {
	PlanetId string // path parameter "planetId"
	Query    url.Values
	Header   http.Header
	Body     []byte // raw JSON request body; nil means none
}

// PlanetsDelete calls DELETE /planets/{planetId}. Delete a planet
func (c *Client) PlanetsDelete(ctx context.Context, req *PlanetsDeleteRequest) (*Response, error) {
	return c.do(ctx, "DELETE", "/planets/"+url.PathEscape(req.PlanetId), req.Query, req.Header, req.Body, [][]string{{"apiKeyCookie"}, {"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"openIdConnect"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// PlanetsGetRequest carries the inputs of GET /planets/{planetId}.
type PlanetsGetRequest struct {
	PlanetId string // path parameter "planetId"
	Query    url.Values
	Header   http.Header
	Body     []byte // raw JSON request body; nil means none
}

// PlanetsGet calls GET /planets/{planetId}. Get a planet
func (c *Client) PlanetsGet(ctx context.Context, req *PlanetsGetRequest) (*Response, error) {
	return c.do(ctx, "GET", "/planets/"+url.PathEscape(req.PlanetId), req.Query, req.Header, req.Body, nil)
}

// PlanetsGetAllDataRequest carries the inputs of GET /planets.
type PlanetsGetAllDataRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// PlanetsGetAllData calls GET /planets. Get all planets
func (c *Client) PlanetsGetAllData(ctx context.Context, req *PlanetsGetAllDataRequest) (*Response, error) {
	return c.do(ctx, "GET", "/planets", req.Query, req.Header, req.Body, nil)
}

// PlanetsImageRequest carries the inputs of POST /planets/{planetId}/image.
type PlanetsImageRequest struct {
	PlanetId string // path parameter "planetId"
	Query    url.Values
	Header   http.Header
	Body     []byte // raw JSON request body; nil means none
}

// PlanetsImage calls POST /planets/{planetId}/image. Upload an image to a planet
func (c *Client) PlanetsImage(ctx context.Context, req *PlanetsImageRequest) (*Response, error) {
	return c.do(ctx, "POST", "/planets/"+url.PathEscape(req.PlanetId)+"/image", req.Query, req.Header, req.Body, [][]string{{"apiKeyCookie"}, {"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"openIdConnect"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// PlanetsUpdateRequest carries the inputs of PUT /planets/{planetId}.
type PlanetsUpdateRequest struct {
	PlanetId string // path parameter "planetId"
	Query    url.Values
	Header   http.Header
	Body     []byte // raw JSON request body; nil means none
}

// PlanetsUpdate calls PUT /planets/{planetId}. Update a planet
func (c *Client) PlanetsUpdate(ctx context.Context, req *PlanetsUpdateRequest) (*Response, error) {
	return c.do(ctx, "PUT", "/planets/"+url.PathEscape(req.PlanetId), req.Query, req.Header, req.Body, [][]string{{"apiKeyCookie"}, {"apiKeyHeader"}, {"apiKeyQuery"}, {"basicAuth"}, {"bearerAuth"}, {"oAuth2"}, {"openIdConnect"}, {"apiKeyHeader", "apiKeyQuery"}})
}

// UserSignupCreateRequest carries the inputs of POST /user/signup.
type UserSignupCreateRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// UserSignupCreate calls POST /user/signup. Create a user
func (c *Client) UserSignupCreate(ctx context.Context, req *UserSignupCreateRequest) (*Response, error) {
	return c.do(ctx, "POST", "/user/signup", req.Query, req.Header, req.Body, nil)
}
