// Code generated by biscuit. DO NOT EDIT.

package client

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// securityScheme describes one components/securitySchemes entry's wire
// application, baked in at generation time.
type securityScheme struct {
	Name       string
	Flag       string
	EnvVar     string
	Type       string // apiKey | http | oauth2 | openIdConnect
	HTTPScheme string // http only: bearer | basic
	In         string // apiKey only: header | query | cookie
	Param      string // apiKey only: the header/query/cookie name
}

var securitySchemes = []securityScheme{
	{Name: "apiKeyCookie", Flag: "api-key-cookie", EnvVar: "GALAXY_API_KEY_COOKIE", Type: "apiKey", HTTPScheme: "", In: "cookie", Param: "api_key"},
	{Name: "apiKeyHeader", Flag: "api-key-header", EnvVar: "GALAXY_API_KEY_HEADER", Type: "apiKey", HTTPScheme: "", In: "header", Param: "X-API-Key"},
	{Name: "apiKeyQuery", Flag: "api-key-query", EnvVar: "GALAXY_API_KEY_QUERY", Type: "apiKey", HTTPScheme: "", In: "query", Param: "api_key"},
	{Name: "basicAuth", Flag: "basic-auth", EnvVar: "GALAXY_BASIC_AUTH", Type: "http", HTTPScheme: "basic", In: "", Param: ""},
	{Name: "bearerAuth", Flag: "bearer-auth", EnvVar: "GALAXY_BEARER_AUTH", Type: "http", HTTPScheme: "bearer", In: "", Param: ""},
	{Name: "oAuth2", Flag: "o-auth2", EnvVar: "GALAXY_O_AUTH2", Type: "oauth2", HTTPScheme: "", In: "", Param: ""},
	{Name: "openIdConnect", Flag: "open-id-connect", EnvVar: "GALAXY_OPEN_ID_CONNECT", Type: "openIdConnect", HTTPScheme: "", In: "", Param: ""},
}

// AuthError marks an operation that requires auth no configured credential
// satisfies; cmdutil.ExitCode maps it onto ExitAuth.
type AuthError struct{ Message string }

func (e *AuthError) Error() string { return e.Message }

// applyAuth attaches every configured credential referenced by security to
// header/query, and fails closed before any network I/O when no alternative
// in security is satisfiable — either by an optional (empty) alternative, or
// by configured credentials for every scheme in some alternative.
func (c *Client) applyAuth(security [][]string, header http.Header, query url.Values) error {
	if len(security) == 0 {
		return nil
	}
	satisfiable := false
	referenced := map[string]bool{}
	for _, alt := range security {
		ok := true
		for _, name := range alt {
			referenced[name] = true
			if c.Credentials[name] == "" {
				ok = false
			}
		}
		if ok {
			satisfiable = true
		}
	}
	if !satisfiable {
		return &AuthError{Message: authErrorMessage(security)}
	}
	for _, s := range securitySchemes {
		v := c.Credentials[s.Name]
		if v == "" || !referenced[s.Name] {
			continue
		}
		applyScheme(s, v, header, query)
	}
	return nil
}

func applyScheme(s securityScheme, v string, header http.Header, query url.Values) {
	switch s.Type {
	case "http":
		if s.HTTPScheme == "basic" {
			header.Set("Authorization", "Basic "+base64.StdEncoding.EncodeToString([]byte(v)))
		} else {
			header.Set("Authorization", "Bearer "+v)
		}
	case "oauth2", "openIdConnect":
		header.Set("Authorization", "Bearer "+v)
	case "apiKey":
		switch s.In {
		case "query":
			query.Set(s.Param, v)
		case "cookie":
			// header is the caller's shared req.Header, and a paginated walk
			// re-invokes the op per page over the same req, so Add would
			// append one copy of this cookie per page.
			pair := s.Param + "=" + v
			if cur := header.Get("Cookie"); cur == "" {
				header.Set("Cookie", pair)
			} else if !strings.Contains(cur, s.Param+"=") {
				header.Set("Cookie", cur+"; "+pair)
			}
		default: // header
			header.Set(s.Param, v)
		}
	}
}

// authErrorMessage names every flag/env var that would satisfy security, so
// the failure is actionable without reading source.
func authErrorMessage(security [][]string) string {
	byName := make(map[string]securityScheme, len(securitySchemes))
	for _, s := range securitySchemes {
		byName[s.Name] = s
	}
	var alts []string
	for _, alt := range security {
		var parts []string
		for _, name := range alt {
			if s, ok := byName[name]; ok {
				parts = append(parts, fmt.Sprintf("--%s (or %s)", s.Flag, s.EnvVar))
			}
		}
		if len(parts) > 0 {
			alts = append(alts, strings.Join(parts, " and "))
		}
	}
	if len(alts) == 0 {
		return "this operation requires authentication"
	}
	return "this operation requires authentication: set " + strings.Join(alts, ", or ")
}
