// Code generated by biscuit. DO NOT EDIT.

// Package mock is a Swagger Petstore test double derived from the spec: every
// operation answers on its own route with a canned, schema-valid response, and
// every request is recorded so tests can assert what went on the wire.
package mock

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"sync"
)

// Recorded is one request the server received, kept verbatim.
type Recorded struct {
	Method string
	Path   string
	Query  url.Values
	Header http.Header
	Body   []byte
}

// route is one operation's canned answer, baked in at generation time.
type route struct {
	method      string
	path        string // path template; a {param} segment matches any one non-empty segment
	status      int
	contentType string
	body        string
	sse         bool
}

// routes is sorted by (path, method), so which route answers a request never
// depends on iteration order.
var routes = []route{
	{method: "GET", path: "/pets", status: 200, contentType: "application/json", body: "[{\"id\":0,\"name\":\"string\"}]"},
	{method: "POST", path: "/pets", status: 201, contentType: "", body: ""},
	{method: "GET", path: "/pets/{petId}", status: 200, contentType: "application/json", body: "{\"id\":0,\"name\":\"string\"}"},
}

// Server is an httptest server answering every operation in the spec.
type Server struct {
	*httptest.Server

	mu       sync.Mutex
	requests []Recorded
}

// New starts a mock server. The caller closes it.
func New() *Server {
	s := &Server{}
	s.Server = httptest.NewServer(http.HandlerFunc(s.serve))
	return s
}

// Requests returns every request received since the last Reset, in order.
func (s *Server) Requests() []Recorded {
	s.mu.Lock()
	defer s.mu.Unlock()
	return append([]Recorded(nil), s.requests...)
}

// Reset drops the recorded requests, so one server can serve many cases.
func (s *Server) Reset() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.requests = nil
}

func (s *Server) serve(w http.ResponseWriter, r *http.Request) {
	body, _ := io.ReadAll(r.Body)
	s.mu.Lock()
	s.requests = append(s.requests, Recorded{
		Method: r.Method,
		Path:   r.URL.Path,
		Query:  r.URL.Query(),
		Header: r.Header.Clone(),
		Body:   body,
	})
	s.mu.Unlock()

	rt, ok := match(r.Method, r.URL.Path)
	if !ok {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]string{
			"error": fmt.Sprintf("no mock route for %s %s", r.Method, r.URL.Path),
		})
		return
	}
	if rt.sse {
		writeEvents(w, rt.status, rt.body)
		return
	}
	if rt.contentType != "" {
		w.Header().Set("Content-Type", rt.contentType)
	}
	w.WriteHeader(rt.status)
	_, _ = io.WriteString(w, rt.body)
}

// match picks the route answering one request: among the routes that match,
// the most literal template wins, so /pets/mine beats /pets/{petId}.
func match(method, path string) (route, bool) {
	best := -1
	var found route
	for _, rt := range routes {
		if rt.method != method || !MatchPath(rt.path, path) {
			continue
		}
		if n := literalSegments(rt.path); n > best {
			best, found = n, rt
		}
	}
	return found, best >= 0
}

// MatchPath reports whether a request path matches a route template, each
// {param} segment matching exactly one non-empty segment.
func MatchPath(template, path string) bool {
	t := strings.Split(strings.Trim(template, "/"), "/")
	p := strings.Split(strings.Trim(path, "/"), "/")
	if len(t) != len(p) {
		return false
	}
	for i, seg := range t {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			if p[i] == "" {
				return false
			}
			continue
		}
		if seg != p[i] {
			return false
		}
	}
	return true
}

func literalSegments(template string) int {
	n := 0
	for _, seg := range strings.Split(template, "/") {
		if !strings.HasPrefix(seg, "{") {
			n++
		}
	}
	return n
}

// writeEvents streams the canned body as two server-sent events followed by
// the [DONE] sentinel, flushing each so a streaming client sees them arrive
// one at a time rather than as one buffered response.
func writeEvents(w http.ResponseWriter, status int, body string) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.WriteHeader(status)
	flusher, _ := w.(http.Flusher)
	data := compactLine(body)
	for _, event := range []string{data, data, "[DONE]"} {
		_, _ = fmt.Fprintf(w, "data: %s\n\n", event)
		if flusher != nil {
			flusher.Flush()
		}
	}
}

// compactLine renders body as a single line so it can ride one data: field.
func compactLine(body string) string {
	var buf bytes.Buffer
	if err := json.Compact(&buf, []byte(body)); err != nil {
		return "{}"
	}
	return buf.String()
}
