// Code generated by biscuit. DO NOT EDIT.

package mock

import (
	"os"
	"strings"
	"testing"

	"github.com/oxmonty/petstore-cli/pkg/cmd"
)

// smokeCase is one generated invocation: the command path plus every flag the
// operation needs, valued from the spec at generation time.
type smokeCase struct {
	name   string
	args   []string
	method string
	path   string // route template the resulting request must match
	pages  bool   // the command walks pages
	stream bool   // the command streams server-sent events
	skip   string // non-empty: why this operation can't be driven generically
}

var smokeCases = []smokeCase{
	{name: "pets list", args: []string{"pets", "list"}, method: "GET", path: "/pets"},
	{name: "pets create", args: []string{"pets", "create", "--id=1", "--name=x"}, method: "POST", path: "/pets"},
	{name: "pets show", args: []string{"pets", "show", "--pet-id=x"}, method: "GET", path: "/pets/{petId}"},
}

// TestSmokeEveryCommand drives every command in the tree against the
// spec-derived mock, in-process: each must succeed and put exactly the request
// its operation describes on the wire.
func TestSmokeEveryCommand(t *testing.T) {
	srv := New()
	defer srv.Close()

	var ran, skipped int
	for _, c := range smokeCases {
		t.Run(c.name, func(t *testing.T) {
			if c.skip != "" {
				skipped++
				t.Skip(c.skip)
			}
			ran++
			srv.Reset()

			args := append(append([]string(nil), c.args...), "--base-url", srv.URL)
			if c.pages {
				// A canned page never shrinks, so an arithmetic (offset/page)
				// walk would advance forever against the mock.
				args = append(args, "--max-pages", "3")
			}
			line := strings.Join(args, " ")

			out, err := captureStdout(t, func() error {
				root := cmd.NewRootCmd("smoke")
				root.SetArgs(args)
				return root.Execute()
			})
			if err != nil {
				t.Fatalf("%s: %v\n%s", line, err, out)
			}

			reqs := srv.Requests()
			if len(reqs) == 0 {
				t.Fatalf("%s: no request reached the mock", line)
			}
			switch {
			case c.pages && len(reqs) > 3:
				t.Errorf("%s: walked %d pages, want the walk bounded at 3", line, len(reqs))
			case !c.pages && len(reqs) != 1:
				t.Errorf("%s: made %d requests, want 1", line, len(reqs))
			}
			if got := reqs[0]; got.Method != c.method || !MatchPath(c.path, got.Path) {
				t.Errorf("%s: wire request = %s %s, want %s %s", line, got.Method, got.Path, c.method, c.path)
			}
			if c.stream && strings.TrimSpace(out) == "" {
				t.Errorf("%s: streaming command printed no events", line)
			}
		})
	}
	if len(smokeCases) > 0 && ran == 0 {
		t.Fatalf("every one of the %d smoke cases skipped", len(smokeCases))
	}
	t.Logf("smoke: %d commands run, %d skipped", ran, skipped)
}

// captureStdout runs fn with the process stdout redirected to a file and
// returns what it printed. The command tree resolves its streams from
// os.Stdout when it is constructed, so fn must build the root command too.
func captureStdout(t *testing.T, fn func() error) (string, error) {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "stdout")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	saved := os.Stdout
	os.Stdout = f
	runErr := fn()
	os.Stdout = saved

	out, err := os.ReadFile(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	return string(out), runErr
}
