// Code generated by biscuit. DO NOT EDIT.

// Package celestialbodies implements the celestial-bodies commands.
package celestialbodies

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/internal/factory"
)

// NewCmdCelestialBodies groups the celestial-bodies subcommands.
func NewCmdCelestialBodies(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "celestial-bodies",
		Short: "Celestial bodies are the planets and satellites in the Scalar Galaxy.",
	}
	cmd.AddCommand(newCelestialBodiesCreateCmd(f))
	return cmd
}

func newCelestialBodiesCreateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a celestial body",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.CelestialBodiesCreateRequest{}
			if cmd.Flags().Changed("body") {
				v, _ := cmd.Flags().GetString("body")
				ev, err := cmdutil.ExpandArg(v)
				if err != nil {
					return fmt.Errorf("--%s: %w", "body", err)
				}
				jv, err := cmdutil.Coerce(ev, "json")
				if err != nil {
					return fmt.Errorf("--%s: %w", "body", err)
				}
				b, err := json.Marshal(jv)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.CelestialBodiesCreate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().String("body", "", "A celestial body which can be either a planet or a satellite")
	_ = cmd.MarkFlagRequired("body")
	return cmd
}
