// Code generated by biscuit. DO NOT EDIT.

package main

import (
	"os"

	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/pkg/cmd"
)

// version is stamped by goreleaser ldflags at release time.
var version = "dev"

func main() {
	err := cmd.NewRootCmd(version).Execute()
	os.Exit(cmdutil.ExitCode(err))
}
