// Code generated by biscuit. DO NOT EDIT.

// Package cmdutil carries the small helpers every generated command shares.
package cmdutil

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/oxmonty/petstore-cli/internal/client"
	"github.com/oxmonty/petstore-cli/internal/iostreams"
)

// SetPath sets value at path inside nested maps, creating levels as needed.
func SetPath(m map[string]any, path []string, value any) {
	for len(path) > 1 {
		next, ok := m[path[0]].(map[string]any)
		if !ok {
			next = map[string]any{}
			m[path[0]] = next
		}
		m = next
		path = path[1:]
	}
	m[path[0]] = value
}

// Coerce converts one flag string into the JSON value its schema type names.
func Coerce(s, typ string) (any, error) {
	switch typ {
	case "integer":
		return strconv.ParseInt(s, 10, 64)
	case "number":
		return strconv.ParseFloat(s, 64)
	case "boolean":
		return strconv.ParseBool(s)
	case "json":
		var v any
		if err := json.Unmarshal([]byte(s), &v); err != nil {
			return nil, fmt.Errorf("invalid JSON: %w", err)
		}
		return v, nil
	default:
		return s, nil
	}
}

// PrintResponse writes the response body and maps HTTP failure onto a
// non-zero exit.
func PrintResponse(ios *iostreams.IOStreams, resp *client.Response) error {
	out := ios.Out
	if resp.Status >= 400 {
		out = ios.ErrOut
	}
	if len(resp.Body) > 0 {
		_, _ = out.Write(resp.Body)
		if resp.Body[len(resp.Body)-1] != '\n' {
			_, _ = io.WriteString(out, "\n")
		}
	}
	if resp.Status >= 400 {
		return fmt.Errorf("API error: HTTP %d", resp.Status)
	}
	return nil
}
