// Code generated by biscuit. DO NOT EDIT.

// Command gendocs writes petstore's man pages and shell completion scripts
// to disk so they can be bundled into release archives and Homebrew casks.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"

	"github.com/oxmonty/petstore-cli/pkg/cmd"
)

func main() {
	dir := flag.String("dir", "", "output directory (man/ and completions/ are created inside it)")
	flag.Parse()
	if *dir == "" {
		fmt.Fprintln(os.Stderr, "gendocs: --dir is required")
		os.Exit(1)
	}

	if err := run(*dir); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	manDir := filepath.Join(dir, "man")
	completionsDir := filepath.Join(dir, "completions")
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(completionsDir, 0o755); err != nil {
		return err
	}

	root := cmd.NewRootCmd("dev")

	header := &doc.GenManHeader{Title: strings.ToUpper("petstore"), Section: "1"}
	if err := doc.GenManTree(root, header, manDir); err != nil {
		return fmt.Errorf("generate man pages: %w", err)
	}

	if err := root.GenBashCompletionFileV2(filepath.Join(completionsDir, "petstore"+".bash"), true); err != nil {
		return fmt.Errorf("generate bash completion: %w", err)
	}
	if err := root.GenZshCompletionFile(filepath.Join(completionsDir, "_"+"petstore")); err != nil {
		return fmt.Errorf("generate zsh completion: %w", err)
	}
	if err := root.GenFishCompletionFile(filepath.Join(completionsDir, "petstore"+".fish"), true); err != nil {
		return fmt.Errorf("generate fish completion: %w", err)
	}
	if err := root.GenPowerShellCompletionFileWithDesc(filepath.Join(completionsDir, "petstore"+".ps1")); err != nil {
		return fmt.Errorf("generate powershell completion: %w", err)
	}

	return nil
}
