// Code generated by biscuit. DO NOT EDIT.

// Package me implements the me commands.
package me

import (
	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/internal/factory"
)

// NewCmdMe groups the me subcommands.
func NewCmdMe(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "me",
		Short: "Operations on me",
	}
	cmd.AddCommand(newMeListCmd(f))
	return cmd
}

func newMeListCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Get authenticated user",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.MeListRequest{}
			resp, err := cl.MeList(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	return cmd
}
