// Code generated by biscuit. DO NOT EDIT.

// Package signup implements the signup commands.
package signup

import (
	"encoding/json"

	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/internal/factory"
)

// NewCmdSignup groups the signup subcommands.
func NewCmdSignup(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "signup",
		Short: "Operations on signup",
	}
	cmd.AddCommand(newUserSignupCreateCmd(f))
	return cmd
}

func newUserSignupCreateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a user",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.UserSignupCreateRequest{}
			body := map[string]any{}
			if cmd.Flags().Changed("email") {
				v, _ := cmd.Flags().GetString("email")
				cmdutil.SetPath(body, []string{"email"}, v)
			}
			if cmd.Flags().Changed("id") {
				v, _ := cmd.Flags().GetInt64("id")
				cmdutil.SetPath(body, []string{"id"}, v)
			}
			if cmd.Flags().Changed("name") {
				v, _ := cmd.Flags().GetString("name")
				cmdutil.SetPath(body, []string{"name"}, v)
			}
			if cmd.Flags().Changed("password") {
				v, _ := cmd.Flags().GetString("password")
				cmdutil.SetPath(body, []string{"password"}, v)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.UserSignupCreate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().String("email", "", "")
	_ = cmd.MarkFlagRequired("email")
	cmd.Flags().Int64("id", 0, "")
	cmd.Flags().String("name", "", "")
	cmd.Flags().String("password", "", "")
	_ = cmd.MarkFlagRequired("password")
	return cmd
}
