// Code generated by biscuit. DO NOT EDIT.

// Package token implements the token commands.
package token

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/internal/factory"
)

// NewCmdToken groups the token subcommands.
func NewCmdToken(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "token",
		Short: "Operations on token",
	}
	cmd.AddCommand(newAuthTokenCreateCmd(f))
	return cmd
}

func newAuthTokenCreateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Get a token",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.AuthTokenCreateRequest{}
			body := map[string]any{}
			if cmd.Flags().Changed("email") {
				v, _ := cmd.Flags().GetString("email")
				ev, err := cmdutil.ExpandArg(v)
				if err != nil {
					return fmt.Errorf("--%s: %w", "email", err)
				}
				cmdutil.SetPath(body, []string{"email"}, ev)
			}
			if cmd.Flags().Changed("password") {
				v, _ := cmd.Flags().GetString("password")
				ev, err := cmdutil.ExpandArg(v)
				if err != nil {
					return fmt.Errorf("--%s: %w", "password", err)
				}
				cmdutil.SetPath(body, []string{"password"}, ev)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.AuthTokenCreate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().String("email", "", "")
	_ = cmd.MarkFlagRequired("email")
	cmd.Flags().String("password", "", "")
	_ = cmd.MarkFlagRequired("password")
	return cmd
}
