package cli

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/oxmonty/biscuit/internal/config"
	"github.com/oxmonty/biscuit/internal/ir"
	"github.com/oxmonty/biscuit/internal/lint"
	"github.com/oxmonty/biscuit/internal/mapping"
	"github.com/oxmonty/biscuit/internal/spec"
)

func newInitCommand() *cobra.Command {
	var specPath string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a starter biscuit.yaml seeded from doctor's gap analysis",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if _, err := os.Stat(config.FileName); err == nil {
				return &usageError{fmt.Errorf("%s already exists; edit it directly or remove it first", config.FileName)}
			}

			path, err := resolveSpecPath(cmd, specPath, nil)
			if err != nil {
				return err
			}
			doc, err := spec.Load(path)
			if err != nil {
				return err
			}
			report := lint.Run(doc)
			api := mapping.Map(doc, nil)

			content := renderInitConfig(path, report, api)
			if err := os.WriteFile(config.FileName, []byte(content), 0o644); err != nil {
				return err
			}
			// the file must load back through the strict loader it targets
			if _, err := config.Load("."); err != nil {
				return fmt.Errorf("init produced an invalid config (this is a biscuit bug): %w", err)
			}

			stubs := strings.Count(content, "#   \"")
			_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "wrote %s (spec %s, grade %d/100, %d override stub%s)\n",
				config.FileName, path, report.Grade, stubs, plural(stubs))
			return nil
		},
	}
	cmd.Flags().StringVar(&specPath, "spec", "", "path to the OpenAPI spec (default: discover it)")
	return cmd
}

// renderInitConfig writes the starter config: real keys for what is known,
// commented stubs for the gaps doctor found — a spec you don't own gets
// rescued here instead of in the spec.
func renderInitConfig(specPath string, report *lint.Report, api *ir.API) string {
	var b strings.Builder
	_, _ = fmt.Fprintf(&b, "# biscuit.yaml — generated by biscuit init (spec grade %d/100, see biscuit doctor)\n", report.Grade)
	b.WriteString("version: 1\nspec:\n")
	_, _ = fmt.Fprintf(&b, "  path: %s\n", specPath)

	b.WriteString("\n# Gate generation on spec quality:\n# lint:\n#   min_grade: 85\n")

	anonymous := collectAnonymousVerbs(api)
	if len(anonymous) > 0 {
		b.WriteString("\n# These operations have no operationId, so their names below are derived\n")
		b.WriteString("# from method + path. Uncomment to rename; the same keys accept\n")
		b.WriteString("# group / ignore / aliases / pagination.\n")
		b.WriteString("# operations:\n")
		for _, a := range anonymous {
			_, _ = fmt.Fprintf(&b, "#   %q:\n#     name: %s\n", a.key, a.name)
		}
	}
	return b.String()
}

type anonymousVerb struct {
	key  string // "METHOD /path" — the override key for id-less operations
	name string // the currently derived verb name, as a starting point
}

func collectAnonymousVerbs(api *ir.API) []anonymousVerb {
	var out []anonymousVerb
	var walk func(cmds []ir.Command)
	take := func(verbs []ir.Verb) {
		for _, v := range verbs {
			if v.OperationID == "" {
				out = append(out, anonymousVerb{key: v.Method + " " + v.Path, name: v.Name})
			}
		}
	}
	walk = func(cmds []ir.Command) {
		for _, c := range cmds {
			take(c.Verbs)
			walk(c.Children)
		}
	}
	walk(api.Commands)
	take(api.RootVerbs)
	sort.Slice(out, func(i, j int) bool { return out[i].key < out[j].key })
	return out
}
