// Code generated by biscuit. DO NOT EDIT.

// Package cmd wires the petstore command tree.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/oxmonty/petstore-cli/internal/client"
	"github.com/oxmonty/petstore-cli/internal/factory"
	"github.com/oxmonty/petstore-cli/internal/iostreams"
	pets "github.com/oxmonty/petstore-cli/pkg/cmd/pets"
)

// NewRootCmd builds the petstore root command.
func NewRootCmd(version string) *cobra.Command {
	f := &factory.Factory{IOStreams: iostreams.System()}
	var baseURL string
	f.Client = func() (*client.Client, error) {
		return &client.Client{BaseURL: baseURL}, nil
	}
	cmd := &cobra.Command{
		Use:          "petstore",
		Short:        "Swagger Petstore",
		Long:         "Quickstart:\n  petstore pets create\n  petstore --help\n\nDocs: https://github.com/oxmonty/petstore-cli",
		Version:      version,
		SilenceUsage: true,
	}
	cmd.PersistentFlags().StringVar(&baseURL, "base-url", "http://petstore.swagger.io/v1", "API base URL")
	cmd.AddCommand(pets.NewCmdPets(f))
	cmd.AddCommand(newUpgradeCmd(version))
	return cmd
}
