// Code generated by biscuit. DO NOT EDIT.

// Package user implements the user commands.
package user

import (
	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/factory"
	usersignup "github.com/oxmonty/galaxy-cli/pkg/cmd/user/signup"
)

// NewCmdUser groups the user subcommands.
func NewCmdUser(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user",
		Short: "Operations on user",
	}
	cmd.AddCommand(usersignup.NewCmdSignup(f))
	return cmd
}
