// Code generated by biscuit. DO NOT EDIT.

// Package cmd wires the galaxy command tree.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/factory"
	"github.com/oxmonty/galaxy-cli/internal/iostreams"
	auth "github.com/oxmonty/galaxy-cli/pkg/cmd/auth"
	celestialbodies "github.com/oxmonty/galaxy-cli/pkg/cmd/celestialbodies"
	me "github.com/oxmonty/galaxy-cli/pkg/cmd/me"
	planets "github.com/oxmonty/galaxy-cli/pkg/cmd/planets"
	user "github.com/oxmonty/galaxy-cli/pkg/cmd/user"
)

// NewRootCmd builds the galaxy root command.
func NewRootCmd(version string) *cobra.Command {
	f := &factory.Factory{IOStreams: iostreams.System()}
	var baseURL string
	f.Client = func() (*client.Client, error) {
		return &client.Client{BaseURL: baseURL}, nil
	}
	cmd := &cobra.Command{
		Use:          "galaxy",
		Short:        "Scalar Galaxy",
		Long:         "The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It's a fictional universe with fictional planets and fictional data.\n\nQuickstart:\n  galaxy auth token create\n  galaxy --help\n\nDocs: https://github.com/oxmonty/galaxy-cli",
		Version:      version,
		SilenceUsage: true,
	}
	cmd.PersistentFlags().StringVar(&baseURL, "base-url", "https://galaxy.scalar.com", "API base URL")
	cmd.AddCommand(auth.NewCmdAuth(f))
	cmd.AddCommand(celestialbodies.NewCmdCelestialBodies(f))
	cmd.AddCommand(me.NewCmdMe(f))
	cmd.AddCommand(planets.NewCmdPlanets(f))
	cmd.AddCommand(user.NewCmdUser(f))
	cmd.AddCommand(newUpgradeCmd(version))
	return cmd
}
