// Code generated by biscuit. DO NOT EDIT.

package cmd

import (
	"archive/tar"
	"archive/zip"
	"bufio"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/cobra"
	"golang.org/x/mod/semver"
)

// Channel-aware upgrade: the *install* channel (brew cellar, npm shim, bare
// binary) decides the mechanism — exec the package manager's own upgrade,
// self-swap only bare binaries — and the *release* channel (stable vs next)
// decides the target. Crossing channels or pinning --version is explicit and
// confirmed when it takes ownership away from a package manager.

const (
	githubRepo    = "oxmonty/galaxy-cli"
	brewCaskShort = "galaxy-cli"
	brewTapPrefix = "oxmonty/tap/"
	npmPackage    = "galaxy-cli"
)

type upgradeOptions struct {
	channel string // "" (keep current), "stable", "next"
	version string // exact pin, with or without leading v
	yes     bool

	// seams for tests
	exePath        func() (string, error)
	apiBase        string // https://api.github.com
	dlBase         string // https://github.com
	execCommand    func(stdout, stderr io.Writer, name string, args ...string) error
	httpClient     *http.Client
	currentVersion string
	goos           string
}

func newUpgradeCmd(currentVersion string) *cobra.Command {
	opts := &upgradeOptions{currentVersion: currentVersion}
	cmd := &cobra.Command{
		Use:     "upgrade",
		Aliases: []string{"update"},
		Short:   "Upgrade galaxy to the latest release on its channel",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			opts.fillDefaults()
			if opts.channel != "" && opts.channel != "stable" && opts.channel != "next" {
				return fmt.Errorf("--channel must be stable or next, got %q", opts.channel)
			}
			return runUpgrade(cmd, opts)
		},
	}
	cmd.Flags().StringVar(&opts.channel, "channel", "", "switch release channel: stable or next")
	cmd.Flags().StringVar(&opts.version, "version", "", "pin an exact release; self-swaps the binary")
	cmd.Flags().BoolVarP(&opts.yes, "yes", "y", false, "skip confirmation prompts")
	return cmd
}

func (o *upgradeOptions) fillDefaults() {
	if o.exePath == nil {
		o.exePath = os.Executable
	}
	if o.apiBase == "" {
		o.apiBase = "https://api.github.com"
	}
	if o.dlBase == "" {
		o.dlBase = "https://github.com"
	}
	if o.execCommand == nil {
		o.execCommand = func(stdout, stderr io.Writer, name string, args ...string) error {
			c := exec.Command(name, args...)
			c.Stdout = stdout
			c.Stderr = stderr
			c.Stdin = os.Stdin
			return c.Run()
		}
	}
	if o.httpClient == nil {
		o.httpClient = http.DefaultClient
	}
	if o.goos == "" {
		o.goos = runtime.GOOS
	}
}

// installChannel is how this galaxy got onto disk.
type installChannel int

const (
	installBare installChannel = iota
	installBrew
	installNPM
)

func detectInstall(exePath string) installChannel {
	p := filepath.ToSlash(exePath)
	switch {
	case strings.Contains(p, "/Caskroom/") || strings.Contains(p, "/Cellar/"):
		return installBrew
	case strings.Contains(p, "/node_modules/"):
		return installNPM
	default:
		return installBare
	}
}

// releaseChannel infers stable vs next. Brew encodes it in the cask path;
// everywhere else a semver prerelease identifier (or a dev build) means next.
func releaseChannel(install installChannel, exePath, current string) string {
	if install == installBrew {
		if strings.Contains(exePath, brewCaskShort+"@next") {
			return "next"
		}
		return "stable"
	}
	if current == "dev" || strings.Contains(current, "-") {
		return "next"
	}
	return "stable"
}

func runUpgrade(cmd *cobra.Command, opts *upgradeOptions) error {
	exePath, err := opts.exePath()
	if err != nil {
		return err
	}
	install := detectInstall(exePath)
	channel := releaseChannel(install, exePath, opts.currentVersion)
	if opts.channel != "" {
		channel = opts.channel
	}
	out, errOut := cmd.OutOrStdout(), cmd.ErrOrStderr()

	// an exact pin always self-swaps — confirm when that takes ownership
	// away from brew/npm
	if opts.version != "" {
		if install != installBare && !opts.yes {
			owner := "Homebrew"
			if install == installNPM {
				owner = "npm"
			}
			ok, err := confirm(cmd, fmt.Sprintf(
				"--version replaces the binary %s manages at %s and takes ownership of it. Continue?", owner, exePath))
			if err != nil {
				return err
			}
			if !ok {
				return fmt.Errorf("aborted")
			}
		}
		return selfSwap(opts, out, exePath, strings.TrimPrefix(opts.version, "v"))
	}

	switch install {
	case installBrew:
		current := brewCaskShort
		if strings.Contains(exePath, brewCaskShort+"@next") {
			current = brewCaskShort + "@next"
		}
		target := brewCaskShort
		if channel == "next" {
			target = brewCaskShort + "@next"
		}
		if current != target {
			if !opts.yes {
				ok, err := confirm(cmd, fmt.Sprintf(
					"switching channels replaces the %s cask with %s. Continue?", current, target))
				if err != nil {
					return err
				}
				if !ok {
					return fmt.Errorf("aborted")
				}
			}
			if err := opts.execCommand(out, errOut, "brew", "uninstall", "--cask", current); err != nil {
				return err
			}
			return opts.execCommand(out, errOut, "brew", "install", "--cask", brewTapPrefix+target)
		}
		return opts.execCommand(out, errOut, "brew", "upgrade", "--cask", target)

	case installNPM:
		tag := "latest"
		if channel == "next" {
			tag = "next"
		}
		return opts.execCommand(out, errOut, "npm", "install", "-g", npmPackage+"@"+tag)

	default:
		tag, err := resolveTag(opts, channel)
		if err != nil {
			return err
		}
		latest := strings.TrimPrefix(tag, "v")
		if opts.currentVersion != "dev" && semver.Compare("v"+latest, "v"+opts.currentVersion) <= 0 {
			_, _ = fmt.Fprintf(out, "galaxy %s is already the newest %s release\n", opts.currentVersion, channel)
			return nil
		}
		return selfSwap(opts, out, exePath, latest)
	}
}

func confirm(cmd *cobra.Command, prompt string) (bool, error) {
	_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "%s [y/N] ", prompt)
	r := bufio.NewReader(cmd.InOrStdin())
	line, err := r.ReadString('\n')
	if err != nil && line == "" {
		return false, nil
	}
	line = strings.ToLower(strings.TrimSpace(line))
	return line == "y" || line == "yes", nil
}

// resolveTag picks the newest tag on a channel. /releases/latest 404s until a
// stable release exists; /releases is newest-first including prereleases.
func resolveTag(opts *upgradeOptions, channel string) (string, error) {
	if channel == "stable" {
		var rel struct {
			TagName string `json:"tag_name"`
		}
		status, err := getJSON(opts, opts.apiBase+"/repos/"+githubRepo+"/releases/latest", &rel)
		if err != nil {
			return "", err
		}
		if status == http.StatusNotFound || rel.TagName == "" {
			return "", fmt.Errorf("no stable release published yet — use --channel next")
		}
		return rel.TagName, nil
	}
	var rels []struct {
		TagName string `json:"tag_name"`
	}
	status, err := getJSON(opts, opts.apiBase+"/repos/"+githubRepo+"/releases", &rels)
	if err != nil {
		return "", err
	}
	if status != http.StatusOK || len(rels) == 0 {
		return "", fmt.Errorf("no releases found for %s", githubRepo)
	}
	return rels[0].TagName, nil
}

func getJSON(opts *upgradeOptions, url string, v any) (int, error) {
	resp, err := opts.httpClient.Get(url)
	if err != nil {
		return 0, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return resp.StatusCode, nil
	}
	return resp.StatusCode, json.NewDecoder(resp.Body).Decode(v)
}

// selfSwap downloads the release archive for this platform, verifies it
// against the release's checksums.txt, and atomically replaces the running
// binary. Bare installs only — brew and npm own their files.
func selfSwap(opts *upgradeOptions, out io.Writer, exePath, ver string) error {
	if opts.goos == "windows" {
		return fmt.Errorf("self-upgrade can't replace a running binary on Windows — download v%s from https://github.com/%s/releases", ver, githubRepo)
	}
	ext := "tar.gz"
	filename := fmt.Sprintf("galaxy_%s_%s_%s.%s", ver, opts.goos, runtime.GOARCH, ext)
	base := opts.dlBase + "/" + githubRepo + "/releases/download/v" + ver

	archive, status, err := download(opts, base+"/"+filename)
	if err != nil {
		return err
	}
	if status == http.StatusNotFound {
		return fmt.Errorf("release v%s not found — see https://github.com/%s/releases", ver, githubRepo)
	}

	sums, status, err := download(opts, base+"/checksums.txt")
	if err != nil {
		return err
	}
	if status != http.StatusOK {
		return fmt.Errorf("release v%s has no checksums.txt; refusing to install unverified binary", ver)
	}
	if err := verifyChecksum(archive, sums, filename); err != nil {
		return err
	}

	binary, err := extractBinary(archive, filename)
	if err != nil {
		return err
	}

	// write beside the target so the rename stays on one filesystem
	tmp, err := os.CreateTemp(filepath.Dir(exePath), ".galaxy-upgrade-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.Write(binary); err != nil {
		return err
	}
	if err := tmp.Chmod(0o755); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp.Name(), exePath); err != nil {
		return err
	}
	_, _ = fmt.Fprintf(out, "upgraded galaxy %s → %s\n", opts.currentVersion, ver)
	return nil
}

func download(opts *upgradeOptions, url string) ([]byte, int, error) {
	resp, err := opts.httpClient.Get(url)
	if err != nil {
		return nil, 0, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, resp.StatusCode, nil
	}
	b, err := io.ReadAll(resp.Body)
	return b, resp.StatusCode, err
}

func verifyChecksum(archive, sums []byte, filename string) error {
	got := hex.EncodeToString(func() []byte { s := sha256.Sum256(archive); return s[:] }())
	for _, line := range strings.Split(string(sums), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[1] == filename {
			if fields[0] != got {
				return fmt.Errorf("checksum mismatch for %s: expected %s, got %s", filename, fields[0], got)
			}
			return nil
		}
	}
	return fmt.Errorf("checksums.txt has no entry for %s", filename)
}

func extractBinary(archive []byte, filename string) ([]byte, error) {
	if strings.HasSuffix(filename, ".zip") {
		zr, err := zip.NewReader(bytes.NewReader(archive), int64(len(archive)))
		if err != nil {
			return nil, err
		}
		for _, f := range zr.File {
			if filepath.Base(f.Name) == "galaxy.exe" {
				rc, err := f.Open()
				if err != nil {
					return nil, err
				}
				defer func() { _ = rc.Close() }()
				return io.ReadAll(rc)
			}
		}
		return nil, fmt.Errorf("galaxy.exe not found in %s", filename)
	}
	gz, err := gzip.NewReader(bytes.NewReader(archive))
	if err != nil {
		return nil, err
	}
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if filepath.Base(hdr.Name) == "galaxy" && hdr.Typeflag == tar.TypeReg {
			return io.ReadAll(tr)
		}
	}
	return nil, fmt.Errorf("galaxy binary not found in %s", filename)
}
