// Code generated by biscuit. DO NOT EDIT.

// Package auth implements the auth commands.
package auth

import (
	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/factory"
	authtoken "github.com/oxmonty/galaxy-cli/pkg/cmd/auth/token"
)

// NewCmdAuth groups the auth subcommands.
func NewCmdAuth(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Operations on auth",
	}
	cmd.AddCommand(authtoken.NewCmdToken(f))
	return cmd
}
