// Code generated by biscuit. DO NOT EDIT.

package client

import (
	"context"
	"net/http"
	"net/url"
)

// PetsCreateRequest carries the inputs of POST /pets.
type PetsCreateRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// PetsCreate calls POST /pets. Create a pet
func (c *Client) PetsCreate(ctx context.Context, req *PetsCreateRequest) (*Response, error) {
	return c.do(ctx, "POST", "/pets", req.Query, req.Header, req.Body)
}

// PetsListRequest carries the inputs of GET /pets.
type PetsListRequest struct {
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// PetsList calls GET /pets. List all pets
func (c *Client) PetsList(ctx context.Context, req *PetsListRequest) (*Response, error) {
	return c.do(ctx, "GET", "/pets", req.Query, req.Header, req.Body)
}

// PetsShowRequest carries the inputs of GET /pets/{petId}.
type PetsShowRequest struct {
	PetId  string // path parameter "petId"
	Query  url.Values
	Header http.Header
	Body   []byte // raw JSON request body; nil means none
}

// PetsShow calls GET /pets/{petId}. Info for a specific pet
func (c *Client) PetsShow(ctx context.Context, req *PetsShowRequest) (*Response, error) {
	return c.do(ctx, "GET", "/pets/"+url.PathEscape(req.PetId), req.Query, req.Header, req.Body)
}
