// Code generated by biscuit. DO NOT EDIT.
module github.com/oxmonty/galaxy-cli

go 1.25.7

require (
	github.com/spf13/cobra v1.10.2
	github.com/tidwall/gjson v1.19.0
	go.yaml.in/yaml/v4 v4.0.0-rc.6
	golang.org/x/mod v0.38.0
)

require (
	github.com/cpuguy83/go-md2man/v2 v2.0.6 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/russross/blackfriday/v2 v2.1.0 // indirect
	github.com/spf13/pflag v1.0.9 // indirect
	github.com/tidwall/match v1.1.1 // indirect
	github.com/tidwall/pretty v1.2.0 // indirect
	go.yaml.in/yaml/v3 v3.0.4 // indirect
)
