// Code generated by biscuit. DO NOT EDIT.

// Package planets implements the planets commands.
package planets

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/oxmonty/galaxy-cli/internal/client"
	"github.com/oxmonty/galaxy-cli/internal/cmdutil"
	"github.com/oxmonty/galaxy-cli/internal/factory"
)

// NewCmdPlanets groups the planets subcommands.
func NewCmdPlanets(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "planets",
		Short: "Everything about planets",
	}
	cmd.AddCommand(newPlanetsCreateCmd(f))
	cmd.AddCommand(newPlanetsDeleteCmd(f))
	cmd.AddCommand(newPlanetsGetCmd(f))
	cmd.AddCommand(newPlanetsGetAllDataCmd(f))
	cmd.AddCommand(newPlanetsImageCmd(f))
	cmd.AddCommand(newPlanetsUpdateCmd(f))
	return cmd
}

func newPlanetsCreateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a planet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsCreateRequest{}
			body := map[string]any{}
			if cmd.Flags().Changed("atmosphere") {
				vs, _ := cmd.Flags().GetStringArray("atmosphere")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "json")
					if err != nil {
						return fmt.Errorf("--%s: %w", "atmosphere", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"atmosphere"}, items)
			}
			if cmd.Flags().Changed("creator.id") {
				v, _ := cmd.Flags().GetInt64("creator.id")
				cmdutil.SetPath(body, []string{"creator", "id"}, v)
			}
			if cmd.Flags().Changed("creator.name") {
				v, _ := cmd.Flags().GetString("creator.name")
				cmdutil.SetPath(body, []string{"creator", "name"}, v)
			}
			if cmd.Flags().Changed("description") {
				v, _ := cmd.Flags().GetString("description")
				cmdutil.SetPath(body, []string{"description"}, v)
			}
			if cmd.Flags().Changed("discovered-at") {
				v, _ := cmd.Flags().GetString("discovered-at")
				cmdutil.SetPath(body, []string{"discoveredAt"}, v)
			}
			if cmd.Flags().Changed("failure-callback-url") {
				v, _ := cmd.Flags().GetString("failure-callback-url")
				cmdutil.SetPath(body, []string{"failureCallbackUrl"}, v)
			}
			if cmd.Flags().Changed("habitability-index") {
				v, _ := cmd.Flags().GetFloat64("habitability-index")
				cmdutil.SetPath(body, []string{"habitabilityIndex"}, v)
			}
			if cmd.Flags().Changed("id") {
				v, _ := cmd.Flags().GetInt64("id")
				cmdutil.SetPath(body, []string{"id"}, v)
			}
			if cmd.Flags().Changed("image") {
				v, _ := cmd.Flags().GetString("image")
				cmdutil.SetPath(body, []string{"image"}, v)
			}
			if cmd.Flags().Changed("last-updated") {
				v, _ := cmd.Flags().GetString("last-updated")
				cmdutil.SetPath(body, []string{"lastUpdated"}, v)
			}
			if cmd.Flags().Changed("name") {
				v, _ := cmd.Flags().GetString("name")
				cmdutil.SetPath(body, []string{"name"}, v)
			}
			if cmd.Flags().Changed("physical-properties.gravity") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.gravity")
				cmdutil.SetPath(body, []string{"physicalProperties", "gravity"}, v)
			}
			if cmd.Flags().Changed("physical-properties.mass") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.mass")
				cmdutil.SetPath(body, []string{"physicalProperties", "mass"}, v)
			}
			if cmd.Flags().Changed("physical-properties.radius") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.radius")
				cmdutil.SetPath(body, []string{"physicalProperties", "radius"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.average") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.average")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "average"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.max") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.max")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "max"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.min") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.min")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "min"}, v)
			}
			if cmd.Flags().Changed("satellites") {
				vs, _ := cmd.Flags().GetStringArray("satellites")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "json")
					if err != nil {
						return fmt.Errorf("--%s: %w", "satellites", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"satellites"}, items)
			}
			if cmd.Flags().Changed("success-callback-url") {
				v, _ := cmd.Flags().GetString("success-callback-url")
				cmdutil.SetPath(body, []string{"successCallbackUrl"}, v)
			}
			if cmd.Flags().Changed("tags") {
				vs, _ := cmd.Flags().GetStringArray("tags")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "string")
					if err != nil {
						return fmt.Errorf("--%s: %w", "tags", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"tags"}, items)
			}
			if cmd.Flags().Changed("type") {
				v, _ := cmd.Flags().GetString("type")
				cmdutil.SetPath(body, []string{"type"}, v)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.PlanetsCreate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().StringArray("atmosphere", nil, "Atmospheric composition")
	cmd.Flags().Int64("creator.id", 0, "")
	cmd.Flags().String("creator.name", "", "")
	cmd.Flags().String("description", "", "")
	cmd.Flags().String("discovered-at", "", "")
	cmd.Flags().String("failure-callback-url", "", "URL which gets invoked upon a failed operation")
	cmd.Flags().Float64("habitability-index", 0, "A score from 0 to 1 indicating potential habitability")
	cmd.Flags().Int64("id", 0, "")
	_ = cmd.MarkFlagRequired("id")
	cmd.Flags().String("image", "", "")
	cmd.Flags().String("last-updated", "", "")
	cmd.Flags().String("name", "", "")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().Float64("physical-properties.gravity", 0, "Surface gravity in Earth g")
	cmd.Flags().Float64("physical-properties.mass", 0, "Mass in Earth masses (must be greater than 0)")
	cmd.Flags().Float64("physical-properties.radius", 0, "Radius in Earth radii (must be greater than 0)")
	cmd.Flags().Float64("physical-properties.temperature.average", 0, "Average temperature in Kelvin")
	cmd.Flags().Float64("physical-properties.temperature.max", 0, "Maximum temperature in Kelvin")
	cmd.Flags().Float64("physical-properties.temperature.min", 0, "Minimum temperature in Kelvin")
	cmd.Flags().StringArray("satellites", nil, "")
	cmd.Flags().String("success-callback-url", "", "URL which gets invoked upon a successful operation")
	cmd.Flags().StringArray("tags", nil, "")
	cmd.Flags().String("type", "", "")
	return cmd
}

func newPlanetsDeleteCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete a planet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsDeleteRequest{}
			{
				v, _ := cmd.Flags().GetInt64("planet-id")
				req.PlanetId = strconv.FormatInt(v, 10)
			}
			resp, err := cl.PlanetsDelete(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().Int64("planet-id", 0, "The ID of the planet to get")
	_ = cmd.MarkFlagRequired("planet-id")
	return cmd
}

func newPlanetsGetCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get a planet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsGetRequest{}
			{
				v, _ := cmd.Flags().GetInt64("planet-id")
				req.PlanetId = strconv.FormatInt(v, 10)
			}
			resp, err := cl.PlanetsGet(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().Int64("planet-id", 0, "The ID of the planet to get")
	_ = cmd.MarkFlagRequired("planet-id")
	return cmd
}

func newPlanetsGetAllDataCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get-all-data",
		Short: "Get all planets",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsGetAllDataRequest{}
			req.Query = url.Values{}
			if cmd.Flags().Changed("limit") {
				v, _ := cmd.Flags().GetInt64("limit")
				req.Query.Set("limit", strconv.FormatInt(v, 10))
			}
			if cmd.Flags().Changed("offset") {
				v, _ := cmd.Flags().GetInt64("offset")
				req.Query.Set("offset", strconv.FormatInt(v, 10))
			}
			resp, err := cl.PlanetsGetAllData(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().Int64("limit", 0, "The number of items to return")
	cmd.Flags().Int64("offset", 0, "The number of items to skip before starting to collect the result set")
	return cmd
}

func newPlanetsImageCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "image",
		Short: "Upload an image to a planet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsImageRequest{}
			{
				v, _ := cmd.Flags().GetInt64("planet-id")
				req.PlanetId = strconv.FormatInt(v, 10)
			}
			body := map[string]any{}
			if cmd.Flags().Changed("image") {
				v, _ := cmd.Flags().GetString("image")
				cmdutil.SetPath(body, []string{"image"}, v)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.PlanetsImage(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().String("image", "", "The image file to upload")
	cmd.Flags().Int64("planet-id", 0, "The ID of the planet to get")
	_ = cmd.MarkFlagRequired("planet-id")
	return cmd
}

func newPlanetsUpdateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update a planet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PlanetsUpdateRequest{}
			{
				v, _ := cmd.Flags().GetInt64("planet-id")
				req.PlanetId = strconv.FormatInt(v, 10)
			}
			body := map[string]any{}
			if cmd.Flags().Changed("atmosphere") {
				vs, _ := cmd.Flags().GetStringArray("atmosphere")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "json")
					if err != nil {
						return fmt.Errorf("--%s: %w", "atmosphere", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"atmosphere"}, items)
			}
			if cmd.Flags().Changed("creator.id") {
				v, _ := cmd.Flags().GetInt64("creator.id")
				cmdutil.SetPath(body, []string{"creator", "id"}, v)
			}
			if cmd.Flags().Changed("creator.name") {
				v, _ := cmd.Flags().GetString("creator.name")
				cmdutil.SetPath(body, []string{"creator", "name"}, v)
			}
			if cmd.Flags().Changed("description") {
				v, _ := cmd.Flags().GetString("description")
				cmdutil.SetPath(body, []string{"description"}, v)
			}
			if cmd.Flags().Changed("discovered-at") {
				v, _ := cmd.Flags().GetString("discovered-at")
				cmdutil.SetPath(body, []string{"discoveredAt"}, v)
			}
			if cmd.Flags().Changed("failure-callback-url") {
				v, _ := cmd.Flags().GetString("failure-callback-url")
				cmdutil.SetPath(body, []string{"failureCallbackUrl"}, v)
			}
			if cmd.Flags().Changed("habitability-index") {
				v, _ := cmd.Flags().GetFloat64("habitability-index")
				cmdutil.SetPath(body, []string{"habitabilityIndex"}, v)
			}
			if cmd.Flags().Changed("id") {
				v, _ := cmd.Flags().GetInt64("id")
				cmdutil.SetPath(body, []string{"id"}, v)
			}
			if cmd.Flags().Changed("image") {
				v, _ := cmd.Flags().GetString("image")
				cmdutil.SetPath(body, []string{"image"}, v)
			}
			if cmd.Flags().Changed("last-updated") {
				v, _ := cmd.Flags().GetString("last-updated")
				cmdutil.SetPath(body, []string{"lastUpdated"}, v)
			}
			if cmd.Flags().Changed("name") {
				v, _ := cmd.Flags().GetString("name")
				cmdutil.SetPath(body, []string{"name"}, v)
			}
			if cmd.Flags().Changed("physical-properties.gravity") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.gravity")
				cmdutil.SetPath(body, []string{"physicalProperties", "gravity"}, v)
			}
			if cmd.Flags().Changed("physical-properties.mass") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.mass")
				cmdutil.SetPath(body, []string{"physicalProperties", "mass"}, v)
			}
			if cmd.Flags().Changed("physical-properties.radius") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.radius")
				cmdutil.SetPath(body, []string{"physicalProperties", "radius"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.average") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.average")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "average"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.max") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.max")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "max"}, v)
			}
			if cmd.Flags().Changed("physical-properties.temperature.min") {
				v, _ := cmd.Flags().GetFloat64("physical-properties.temperature.min")
				cmdutil.SetPath(body, []string{"physicalProperties", "temperature", "min"}, v)
			}
			if cmd.Flags().Changed("satellites") {
				vs, _ := cmd.Flags().GetStringArray("satellites")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "json")
					if err != nil {
						return fmt.Errorf("--%s: %w", "satellites", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"satellites"}, items)
			}
			if cmd.Flags().Changed("success-callback-url") {
				v, _ := cmd.Flags().GetString("success-callback-url")
				cmdutil.SetPath(body, []string{"successCallbackUrl"}, v)
			}
			if cmd.Flags().Changed("tags") {
				vs, _ := cmd.Flags().GetStringArray("tags")
				items := make([]any, 0, len(vs))
				for _, s := range vs {
					jv, err := cmdutil.Coerce(s, "string")
					if err != nil {
						return fmt.Errorf("--%s: %w", "tags", err)
					}
					items = append(items, jv)
				}
				cmdutil.SetPath(body, []string{"tags"}, items)
			}
			if cmd.Flags().Changed("type") {
				v, _ := cmd.Flags().GetString("type")
				cmdutil.SetPath(body, []string{"type"}, v)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.PlanetsUpdate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().StringArray("atmosphere", nil, "Atmospheric composition")
	cmd.Flags().Int64("creator.id", 0, "")
	cmd.Flags().String("creator.name", "", "")
	cmd.Flags().String("description", "", "")
	cmd.Flags().String("discovered-at", "", "")
	cmd.Flags().String("failure-callback-url", "", "URL which gets invoked upon a failed operation")
	cmd.Flags().Float64("habitability-index", 0, "A score from 0 to 1 indicating potential habitability")
	cmd.Flags().Int64("id", 0, "")
	_ = cmd.MarkFlagRequired("id")
	cmd.Flags().String("image", "", "")
	cmd.Flags().String("last-updated", "", "")
	cmd.Flags().String("name", "", "")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().Float64("physical-properties.gravity", 0, "Surface gravity in Earth g")
	cmd.Flags().Float64("physical-properties.mass", 0, "Mass in Earth masses (must be greater than 0)")
	cmd.Flags().Float64("physical-properties.radius", 0, "Radius in Earth radii (must be greater than 0)")
	cmd.Flags().Float64("physical-properties.temperature.average", 0, "Average temperature in Kelvin")
	cmd.Flags().Float64("physical-properties.temperature.max", 0, "Maximum temperature in Kelvin")
	cmd.Flags().Float64("physical-properties.temperature.min", 0, "Minimum temperature in Kelvin")
	cmd.Flags().Int64("planet-id", 0, "The ID of the planet to get")
	_ = cmd.MarkFlagRequired("planet-id")
	cmd.Flags().StringArray("satellites", nil, "")
	cmd.Flags().String("success-callback-url", "", "URL which gets invoked upon a successful operation")
	cmd.Flags().StringArray("tags", nil, "")
	cmd.Flags().String("type", "", "")
	return cmd
}
