// Code generated by biscuit. DO NOT EDIT.

// Package iostreams centralizes the process IO — the single place TTY
// detection, color, and paging decisions live.
package iostreams

import (
	"io"
	"os"
)

type IOStreams struct {
	In     io.Reader
	Out    io.Writer
	ErrOut io.Writer
}

// System returns the process's real streams.
func System() *IOStreams {
	return &IOStreams{In: os.Stdin, Out: os.Stdout, ErrOut: os.Stderr}
}

// IsStdoutTTY reports whether stdout is a terminal — the switch color and
// pager behavior key off.
func (s *IOStreams) IsStdoutTTY() bool {
	f, ok := s.Out.(*os.File)
	if !ok {
		return false
	}
	info, err := f.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}
