// Package render executes the embedded template tree over the IR, producing
// the complete file plan for a generated repository. Rendering is pure —
// []File in memory; Write materializes a plan under the regeneration-safety
// rules (markers, internal/custom/ emitted once).
package render

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"text/template"

	"golang.org/x/tools/imports"

	"github.com/oxmonty/biscuit/internal/config"
	"github.com/oxmonty/biscuit/internal/ir"
	"github.com/oxmonty/biscuit/templates"
)

// Marker is the generated-file header line. Files whose on-disk copy lacks it
// are treated as user-owned and never rewritten. No biscuit version inside —
// golden bytes must not churn on biscuit releases.
const Marker = "Code generated by biscuit. DO NOT EDIT."

type File struct {
	Path       string // slash-separated, relative to the output dir
	Contents   []byte
	Executable bool
	EmitOnce   bool // written when absent, never overwritten (internal/custom/)
}

// Provenance records where the spec came from, written to .biscuit-state.yml.
type Provenance struct {
	SpecPath   string
	SpecSHA256 string
}

// Render produces the full file plan. One render unit per output file — the
// invariant that will let the unit loop fan out with no locking once the
// benchmark asks for it (PRD: generation pipeline). Sequential today.
func Render(api *ir.API, cfg *config.Config, prov Provenance) ([]File, error) {
	m := buildModel(api, cfg, prov)

	tpl, err := template.New("repo").Funcs(template.FuncMap{
		"q": strconv.Quote,
		// ob/cb emit literal "{{"/"}}" so release templates can carry
		// goreleaser's own {{.Version}} and GitHub Actions' ${{ }} syntax
		// without biscuit's renderer trying to evaluate them as actions.
		"ob": func() string { return "{{" },
		"cb": func() string { return "}}" },
	}).ParseFS(templates.FS, "repo/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("parsing templates: %w", err)
	}

	type unit struct {
		tmpl     string
		path     string
		data     any
		goSource bool
		emitOnce bool
	}
	units := []unit{
		{tmpl: "go.mod.tmpl", path: "go.mod", data: m},
		{tmpl: "go.sum.tmpl", path: "go.sum", data: m},
		{tmpl: "gitignore.tmpl", path: ".gitignore", data: m},
		{tmpl: "biscuit-state.yml.tmpl", path: ".biscuit-state.yml", data: m},
		{tmpl: "main.go.tmpl", path: "cmd/" + m.Binary + "/main.go", data: m, goSource: true},
		{tmpl: "client.go.tmpl", path: "internal/client/client.go", data: m, goSource: true},
		{tmpl: "operations.go.tmpl", path: "internal/client/operations.go", data: m, goSource: true},
		{tmpl: "cmdutil.go.tmpl", path: "internal/cmdutil/cmdutil.go", data: m, goSource: true},
		{tmpl: "iostreams.go.tmpl", path: "internal/iostreams/iostreams.go", data: m, goSource: true},
		{tmpl: "factory.go.tmpl", path: "internal/factory/factory.go", data: m, goSource: true},
		{tmpl: "custom.go.tmpl", path: "internal/custom/custom.go", data: m, goSource: true, emitOnce: true},
		{tmpl: "root.go.tmpl", path: "pkg/cmd/root.go", data: m, goSource: true},
		{tmpl: "goreleaser.yml.tmpl", path: ".goreleaser.yaml", data: m},
		{tmpl: "workflows-ci.yaml.tmpl", path: ".github/workflows/ci.yaml", data: m},
		{tmpl: "workflows-release.yaml.tmpl", path: ".github/workflows/release.yaml", data: m},
		{tmpl: "release-please-config.json.tmpl", path: "release-please-config.json", data: m},
		// emitOnce: release-please's bot owns the manifest after the first
		// release — regeneration must never reset it to 0.0.0
		{tmpl: "release-please-manifest.json.tmpl", path: ".release-please-manifest.json", data: m, emitOnce: true},
	}
	for _, r := range m.AllResources {
		units = append(units, unit{
			tmpl: "resource.go.tmpl",
			path: r.Dir + "/" + r.PkgName + ".go",
			data: struct {
				*repoModel
				Res *resourceView
			}{m, r},
			goSource: true,
		})
	}

	files := make([]File, 0, len(units))
	for _, u := range units {
		var buf bytes.Buffer
		if err := tpl.ExecuteTemplate(&buf, u.tmpl, u.data); err != nil {
			return nil, fmt.Errorf("rendering %s: %w", u.path, err)
		}
		contents := buf.Bytes()
		if u.goSource {
			// goimports prunes each template's superset import list and
			// formats; unresolved identifiers never occur, so no lookups
			contents, err = imports.Process(u.path, contents, nil)
			if err != nil {
				return nil, fmt.Errorf("formatting %s: %w", u.path, err)
			}
		}
		files = append(files, File{Path: u.path, Contents: contents, EmitOnce: u.emitOnce})
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// WriteResult reports what Write actually touched.
type WriteResult struct {
	Written         []string
	SkippedCustom   []string // EmitOnce files that already existed
	SkippedUnmarked []string // existing files without the marker: user-owned
}

// WriteFiles materializes a plan under dir. Regeneration touches only marked
// files: an existing file without the marker has been taken over by the user
// (or never carried one) and is left alone — except when the planned contents
// carry no marker either (go.sum can't hold comments; it stays machine-owned).
func WriteFiles(dir string, files []File) (*WriteResult, error) {
	res := &WriteResult{}
	for _, f := range files {
		target := filepath.Join(dir, filepath.FromSlash(f.Path))
		existing, err := os.ReadFile(target)
		exists := err == nil
		if err != nil && !os.IsNotExist(err) {
			return nil, err
		}
		switch {
		case exists && f.EmitOnce:
			res.SkippedCustom = append(res.SkippedCustom, f.Path)
			continue
		case exists && !bytes.Contains(existing, []byte(Marker)) && bytes.Contains(f.Contents, []byte(Marker)):
			res.SkippedUnmarked = append(res.SkippedUnmarked, f.Path)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return nil, err
		}
		mode := os.FileMode(0o644)
		if f.Executable {
			mode = 0o755
		}
		if err := os.WriteFile(target, f.Contents, mode); err != nil {
			return nil, err
		}
		res.Written = append(res.Written, f.Path)
	}
	return res, nil
}
