package render

import (
	"strings"
	"testing"

	"go.yaml.in/yaml/v4"

	"github.com/oxmonty/biscuit/internal/config"
	"github.com/oxmonty/biscuit/internal/mapping"
	"github.com/oxmonty/biscuit/internal/spec"
)

func TestRenderReadmeFromSource(t *testing.T) {
	// given: petstore rendered without homebrew distribution
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{Output: config.Output{Module: "example.com/petstore-cli"}}
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: the README carries the marker, a from-source install block, usage
	// and completions sections, and no homebrew section
	readme := string(findFile(t, files, "README.md").Contents)
	for _, want := range []string{
		"<!-- Code generated by biscuit. DO NOT EDIT. -->",
		"# swagger-petstore",
		"go install example.com/petstore-cli/cmd/swagger-petstore@latest",
		"swagger-petstore --help",
		"swagger-petstore completion bash|zsh|fish|powershell",
	} {
		if !strings.Contains(readme, want) {
			t.Errorf("README.md missing %q:\n%s", want, readme)
		}
	}
	if strings.Contains(readme, "Homebrew 6") {
		t.Error("README.md documents the Homebrew trust step with Homebrew=false")
	}
}

func TestRenderReadmeHomebrewTapTrust(t *testing.T) {
	// given: the same spec with homebrew distribution enabled
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{
		Output:       config.Output{Module: "github.com/acme/petstore-cli"},
		Distribution: config.Distribution{Homebrew: true},
	}
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: the tap-trust step and the fully-qualified bypass form both appear
	readme := string(findFile(t, files, "README.md").Contents)
	for _, want := range []string{
		"brew tap --trust acme/tap",
		"brew install acme/tap/swagger-petstore-cli",
	} {
		if !strings.Contains(readme, want) {
			t.Errorf("README.md missing %q:\n%s", want, readme)
		}
	}
}

func TestRenderMakefileOmitsDescriptionWhenEmpty(t *testing.T) {
	// given: petstore has no info.description and no output.description override
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{Output: config.Output{Module: "example.com/petstore-cli"}}
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: the help header prints the binary name but no description line
	makefile := string(findFile(t, files, "Makefile").Contents)
	if !strings.Contains(makefile, "\t@printf \"\\n\\033[1mswagger-petstore\\033[0m\\n\"") {
		t.Errorf("Makefile missing the binary-name help header:\n%s", makefile)
	}
	if strings.Contains(makefile, `@printf "%s\n"`) {
		t.Errorf("Makefile printed a description line with no description available:\n%s", makefile)
	}
}

func TestRenderMakefileDescriptionEscaping(t *testing.T) {
	// given: an output.description override with a shell-hostile apostrophe
	// and a dollar sign
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{Output: config.Output{
		Module:      "example.com/petstore-cli",
		Description: "It's $5 well spent",
	}}
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: "'" is closed/escaped/reopened and "$" is doubled so Make hands
	// the shell one literal "$" — both required for the recipe to run at all
	makefile := string(findFile(t, files, "Makefile").Contents)
	if !strings.Contains(makefile, `'It'\''s $$5 well spent'`) {
		t.Errorf("Makefile did not escape the description for Make+shell:\n%s", makefile)
	}
}

func TestRootLongQuickstart(t *testing.T) {
	// given: petstore resolved to a real github.com module
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{Output: config.Output{Module: "github.com/acme/petstore-cli"}}
	m := buildModel(api, cfg, Provenance{})
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: root.go's Long carries the quickstart lines and a docs link
	root := string(findFile(t, files, "pkg/cmd/root.go").Contents)
	for _, want := range []string{
		"Quickstart:",
		m.Binary + " " + m.ExampleUse(),
		m.Binary + " --help",
		"Docs: https://github.com/acme/petstore-cli",
	} {
		if !strings.Contains(root, want) {
			t.Errorf("root.go missing %q:\n%s", want, root)
		}
	}

	// when: the module doesn't resolve to a github.com owner/repo
	filesLocal, err := Render(api, &config.Config{}, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: no docs link is printed for the unresolved "OWNER" placeholder
	rootLocal := string(findFile(t, filesLocal, "pkg/cmd/root.go").Contents)
	if strings.Contains(rootLocal, "Docs:") {
		t.Error("root.go printed a docs link with an unresolved module owner")
	}
}

func TestGoreleaserManpagesMatchTopLevelCommands(t *testing.T) {
	// given: a petstore spec rendered with homebrew distribution enabled
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{
		Output:       config.Output{Module: "github.com/acme/petstore-cli"},
		Distribution: config.Distribution{Homebrew: true},
	}
	m := buildModel(api, cfg, Provenance{})
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// when: parsing the stable cask's manpages list
	goreleaser := findFile(t, files, ".goreleaser.yaml")
	var doc2 map[string]any
	if err := yaml.Unmarshal(goreleaser.Contents, &doc2); err != nil {
		t.Fatalf(".goreleaser.yaml did not parse: %v\n%s", err, goreleaser.Contents)
	}
	casks, _ := doc2["homebrew_casks"].([]any)
	if len(casks) == 0 {
		t.Fatal(".goreleaser.yaml has no homebrew_casks")
	}
	cask, _ := casks[0].(map[string]any)
	got, _ := cask["manpages"].([]any)

	// then: it's exactly root + one page per top-level resource/root verb —
	// every page cobra's GenManTree actually emits for a root command built
	// without ever calling Execute() (no auto-added completion command yet)
	want := []string{"man/" + m.Binary + ".1"}
	for _, r := range m.Resources {
		want = append(want, "man/"+m.Binary+"-"+r.Name+".1")
	}
	for _, v := range m.RootVerbs {
		want = append(want, "man/"+m.Binary+"-"+v.Use+".1")
	}
	if len(got) != len(want) {
		t.Fatalf("manpages = %v, want %v", got, want)
	}
	for i, g := range got {
		if gs, _ := g.(string); gs != want[i] {
			t.Errorf("manpages[%d] = %q, want %q", i, gs, want[i])
		}
	}
}

func TestGendocsImportsCobraDoc(t *testing.T) {
	// given: petstore rendered into a repo that generates its own man pages
	doc, err := spec.Load(ladder + "petstore.yaml")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	api := mapping.Map(doc, nil)
	cfg := &config.Config{Output: config.Output{Module: "github.com/acme/petstore-cli"}}
	files, err := Render(api, cfg, Provenance{SpecPath: "petstore.yaml", SpecSHA256: "test"})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// then: scripts/gendocs/main.go builds the repo's own root command and
	// calls into cobra/doc — the same mechanism biscuit's own gendocs proves
	gendocs := string(findFile(t, files, "scripts/gendocs/main.go").Contents)
	for _, want := range []string{
		`"github.com/spf13/cobra/doc"`,
		`"github.com/acme/petstore-cli/pkg/cmd"`,
		"cmd.NewRootCmd(",
		"doc.GenManTree(",
	} {
		if !strings.Contains(gendocs, want) {
			t.Errorf("scripts/gendocs/main.go missing %q:\n%s", want, gendocs)
		}
	}
}
