// Code generated by biscuit. DO NOT EDIT.

// Package pets implements the pets commands.
package pets

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/oxmonty/petstore-cli/internal/client"
	"github.com/oxmonty/petstore-cli/internal/cmdutil"
	"github.com/oxmonty/petstore-cli/internal/factory"
)

// NewCmdPets groups the pets subcommands.
func NewCmdPets(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pets",
		Short: "Operations on pets",
	}
	cmd.AddCommand(newPetsCreateCmd(f))
	cmd.AddCommand(newPetsListCmd(f))
	cmd.AddCommand(newPetsShowCmd(f))
	return cmd
}

func newPetsCreateCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a pet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PetsCreateRequest{}
			body := map[string]any{}
			if cmd.Flags().Changed("id") {
				v, _ := cmd.Flags().GetInt64("id")
				cmdutil.SetPath(body, []string{"id"}, v)
			}
			if cmd.Flags().Changed("name") {
				v, _ := cmd.Flags().GetString("name")
				ev, err := cmdutil.ExpandArg(v)
				if err != nil {
					return fmt.Errorf("--%s: %w", "name", err)
				}
				cmdutil.SetPath(body, []string{"name"}, ev)
			}
			if cmd.Flags().Changed("tag") {
				v, _ := cmd.Flags().GetString("tag")
				ev, err := cmdutil.ExpandArg(v)
				if err != nil {
					return fmt.Errorf("--%s: %w", "tag", err)
				}
				cmdutil.SetPath(body, []string{"tag"}, ev)
			}
			if len(body) > 0 {
				b, err := json.Marshal(body)
				if err != nil {
					return err
				}
				req.Body = b
			}
			resp, err := cl.PetsCreate(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().Int64("id", 0, "")
	_ = cmd.MarkFlagRequired("id")
	cmd.Flags().String("name", "", "")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().String("tag", "", "")
	return cmd
}

func newPetsListCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List all pets",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PetsListRequest{}
			req.Query = url.Values{}
			if cmd.Flags().Changed("limit") {
				v, _ := cmd.Flags().GetInt64("limit")
				req.Query.Set("limit", strconv.FormatInt(v, 10))
			}
			resp, err := cl.PetsList(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().Int64("limit", 0, "How many items to return at one time (max 100)")
	return cmd
}

func newPetsShowCmd(f *factory.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show",
		Short: "Info for a specific pet",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cl, err := f.Client()
			if err != nil {
				return err
			}
			req := &client.PetsShowRequest{}
			{
				v, _ := cmd.Flags().GetString("pet-id")
				req.PetId = v
			}
			resp, err := cl.PetsShow(cmd.Context(), req)
			if err != nil {
				return err
			}
			return cmdutil.PrintResponse(f.IOStreams, resp, f.Output())
		},
	}
	cmd.Flags().String("pet-id", "", "The id of the pet to retrieve")
	_ = cmd.MarkFlagRequired("pet-id")
	return cmd
}
